### ISSUE TITLE
TODO: Fail the Travis build if a performance regression is detected

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/ModelSanitizer.jl#24]
- [x] 1. Write a benchmark suite
- [x] 2. Run the benchmark suite as part of every Travis build
- [x] 3. Compare the benchmark performance of the `staging`/`trying` Travis build to the benchmark performance of the last commit on `master`
- [x] 4. If the benchmark performance has worsened, fail the `staging`/`trying` Travis build.

**Comment by DilumAluthge** [comment]
This is now implemented on the `master-benchmark` branch. Once the `master-benchmark` branch has been merged into the `master` branch, I will close this issue.
